
version: "3.5"
services:
  web-fe:
    build: .
    command: npm start
    ports:
      - target: 3000
        published: 3001
    networks:
      - counter-net
  jserver:
    build:
        context: .
        dockerfile: server.Dockerfile
    command: db.json
    ports:
      - target: 8080
        published: 3000
    networks:
      counter-net:

networks:
  counter-net:

volumes:
  counter-vol: